### ISSUE TITLE
ARK v0.3.0 New Operators

### ISSUE THREAD

**Issue by chhwang** [microsoft/ark#107]
* ~~[ ] `int8` type support in many operators (#72)~~ moved to the next version plan
* [x] `bfloat16` type support in many operators (#142)
* [x] **embedding:** add support (#122)
* [x] **cast:** add support (#127)
