### ISSUE TITLE
ARK v0.2.0 New Operators

### ISSUE THREAD

**Issue by chhwang** [microsoft/ark#62]
* [x] **matmul:** support `float` (#67)
* [x] **reduce:** support `float` (#67)
* [x] **sub:** add support (#73)
* [x] **div:** add support (#73)
* [x] **sqrt:** add support (#73)
* [x] **exp:** add support (#73)
* [x] **sigmoid:** add support (#73)
* [x] **relu:** support more types (#73)
* [x] **gelu:** support more types (#73)
* ~~[ ] `int8` type support in many operators (#72)~~ moved to the next version release
* [x] **rmsnorm:** add support (#95)
* [x] **rope:** add support (#95)
* [x] **scale:** support `float` (#95)
